language: go

env:
- GIMME_OS=linux GIMME_ARCH=arm GIMME_GOARM=7
go:
- '1.10'

script:
- export ARCH=arm
- export ARM=7
- cd monitor
- go build
after_script:
- ls -l $HOME/gopath/src/github.com/jormenjanssen/rm-watchdog

deploy:
  provider: releases
  api_key:
    secure: pJzRZQFlQ7uTPpIlZzcMwfxktkhB3uEIpGhudiuHURtBZLUMp/ObX51Z4UoEBkr4OSz/Wkg+1JH7B9SjVraVeEG7EJK9wWTMZn8J9hFwbfbX6g5Sat7YxSQAUzoupPY/9f7UQzfGn9RUlKH9TiaKgN3YqM6MS3+C/2RKfq/iW89Vx2c1gBlGsHh0eLghi5jWFzReXZifcs3G3w8QjWUAlpW76xV6CVSCTKLeyXVwDkdHoxEIpo8QnoaGV1m2ZsdZ6Ok0jBPPiuYoFBlWeh1YVpirq4sFKwzrQyjE03itovvliqhkD36kcLmNXZF0UoA4xABWRWiONhRMQWxpjLceKOoDY+7dcn7MLOFfcTUZ1rpru4Nsg2oRQKovLgQD9gc6VOPF1siEhQNIuFn/udTqwOG40iRNoqnrfyjiNkfLnvjrzWVBzTXXpGVqkUw2LZ2m8SyvrcUf3UEWTE70mqtoQR5+MXpdNjUPXF8WuMF0hE00QbHS9Padqmi7dj/eBpqdWQOlF60KwSOT/8hSFePud46JAD7cAm/UbsV5lRi+FtUm6qoOaA6xCPRGf86x79VX38Q5p27Rxl28SXnp7RQk1DMnBnEtcTCvfzMF3Caq/jnyWd5AS6/BXriP3D26ruibD2eC3ekw9uyAZ5eF3IzFCWyI3aOQmqETFWALRmCJAkM=
  file: rm-watchdog
  skip_cleanup: true
